<a href="https://colab.research.google.com/github/DanielMasierra/Python_Oracle_Alura/blob/main/inmuebles_cdmx.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pandas**

## **Importando la base de datos**

In [15]:
import pandas as pd

url = 'https://gist.githubusercontent.com/ahcamachod/a572cfcc2527046db93101f88011b26e/raw/ffb13f45a79d31223e645611a119397dd127ee3c/alquiler.csv'

pd.read_csv(url)

      Tipo;Colonia;Habitaciones;Garages;Suites;Area;Valor;Condominio;Impuesto
0          Cocineta;Condesa;1;0;0;40;5950.0;1750.0;210.0
1                       Casa;Polanco;2;0;1;100;24500.0;;
2      Conjunto Comercial/Sala;Santa Fe;0;4;0;150;182...
3      Departamento;Centro Histórico;1;0;0;15;2800.0;...
4          Departamento;Del Valle;1;0;0;48;2800.0;805.0;
...                                                  ...
25116  Cochera/Estacionamiento;Centro Histórico;0;0;0...
25117  Cocineta;Centro Histórico;0;0;0;27;2800.0;1225...
25118  Departamento;Mixcoac;2;1;0;48;4900.0;1781.5;129.5
25119  Departamento;Lomas de Chapultepec;2;0;0;70;105...
25120  Conjunto Comercial/Sala;Centro Histórico;0;0;0...

[25121 rows x 1 columns]

In [16]:
pd.read_csv(url, sep=';')

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
0,Cocineta,Condesa,1,0,0,40,5950.0,1750.0,210.0
1,Casa,Polanco,2,0,1,100,24500.0,NaN,NaN
2,Conjunto Comercial/Sala,Santa Fe,0,4,0,150,18200.0,14070.0,3888.5
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN
...,...,...,...,...,...,...,...,...,...
25116,Cochera/Estacionamiento,Centro Histórico,0,0,0,755,49000.0,NaN,NaN
25117,Cocineta,Centro Histórico,0,0,0,27,2800.0,1225.0,87.5
25118,Departamento,Mixcoac,2,1,0,48,4900.0,1781.5,129.5
25119,Departamento,Lomas de Chapultepec,2,0,0,70,10500.0,2660.0,NaN
25120,Conjunto Comercial/Sala,Centro Histórico,0,0,0,250,22750.0,14721.0,3881.5

In [17]:
datos = pd.read_csv(url, sep=';')
datos

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
0,Cocineta,Condesa,1,0,0,40,5950.0,1750.0,210.0
1,Casa,Polanco,2,0,1,100,24500.0,NaN,NaN
2,Conjunto Comercial/Sala,Santa Fe,0,4,0,150,18200.0,14070.0,3888.5
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN
...,...,...,...,...,...,...,...,...,...
25116,Cochera/Estacionamiento,Centro Histórico,0,0,0,755,49000.0,NaN,NaN
25117,Cocineta,Centro Histórico,0,0,0,27,2800.0,1225.0,87.5
25118,Departamento,Mixcoac,2,1,0,48,4900.0,1781.5,129.5
25119,Departamento,Lomas de Chapultepec,2,0,0,70,10500.0,2660.0,NaN
25120,Conjunto Comercial/Sala,Centro Histórico,0,0,0,250,22750.0,14721.0,3881.5

In [18]:
datos.head()

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
0,Cocineta,Condesa,1,0,0,40,5950.0,1750.0,210.0
1,Casa,Polanco,2,0,1,100,24500.0,NaN,NaN
2,Conjunto Comercial/Sala,Santa Fe,0,4,0,150,18200.0,14070.0,3888.5
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN

In [19]:
datos.tail()

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
25116,Cochera/Estacionamiento,Centro Histórico,0,0,0,755,49000.0,NaN,NaN
25117,Cocineta,Centro Histórico,0,0,0,27,2800.0,1225.0,87.5
25118,Departamento,Mixcoac,2,1,0,48,4900.0,1781.5,129.5
25119,Departamento,Lomas de Chapultepec,2,0,0,70,10500.0,2660.0,NaN
25120,Conjunto Comercial/Sala,Centro Histórico,0,0,0,250,22750.0,14721.0,3881.5

In [20]:
datos.head(10)

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
0,Cocineta,Condesa,1,0,0,40,5950.0,1750.0,210.0
1,Casa,Polanco,2,0,1,100,24500.0,NaN,NaN
2,Conjunto Comercial/Sala,Santa Fe,0,4,0,150,18200.0,14070.0,3888.5
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN
5,Casa de Condominio,Santa Fe,5,4,5,750,77000.0,NaN,NaN
6,Conjunto Comercial/Sala,Centro Histórico,0,3,0,695,122500.0,67175.5,10605.0
7,Departamento,Centro Histórico,1,0,0,36,4200.0,NaN,NaN
8,Departamento,Condesa,1,0,1,40,7000.0,1963.5,175.0
9,Cocineta,Condesa,1,0,0,27,6300.0,1753.5,NaN

In [21]:
datos.sample(10)

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
22150,Departamento,Bosques de las Lomas,2,1,1,95,13300.0,6300.0,1050.0
11138,Departamento,Lomas de Chapultepec,4,2,2,250,32200.0,10500.0,NaN
21552,Departamento,Condesa,1,1,0,25,6650.0,2275.0,70.0
8811,Conjunto Comercial/Sala,Centro Histórico,0,0,0,25,1575.0,1750.0,297.5
11830,Conjunto Comercial/Sala,Centro Histórico,0,0,0,36,5250.0,3150.0,280.0
17028,Departamento,Del Valle,3,1,1,260,26950.0,7000.0,2800.0
17249,Departamento,San Jerónimo,2,1,0,96,9100.0,2975.0,651.0
8101,Departamento,Roma,3,1,1,120,17500.0,3080.0,759.5
23879,Departamento,Peralvillo,3,1,1,70,4900.0,1708.0,266.0
4605,Cochera/Estacionamiento,Centro Histórico,0,0,0,0,1925.0,NaN,NaN

In [22]:
type(datos)

pandas.core.frame.DataFrame

**Exploración inicial de los datos**

In [23]:
datos.shape

(25121, 9)

In [24]:
datos.columns

Index(['Tipo', 'Colonia', 'Habitaciones', 'Garages', 'Suites', 'Area', 'Valor',
       'Condominio', 'Impuesto'],
      dtype='object')

In [25]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25121 entries, 0 to 25120
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Tipo          25121 non-null  object
 1   Colonia       25121 non-null  object
 2   Habitaciones  25121 non-null  int64
 3   Garages       25121 non-null  int64
 4   Suites        25121 non-null  int64
 5   Area          25121 non-null  int64
 6   Valor         25107 non-null  float64
 7   Condominio    22495 non-null  float64
 8   Impuesto      18037 non-null  float64
dtypes: float64(3), int64(4), object(2)
memory usage: 1.7+ MB

In [26]:
datos['Tipo']

0                       Cocineta
1                           Casa
2        Conjunto Comercial/Sala
3                   Departamento
4                   Departamento
                  ...
25116    Cochera/Estacionamiento
25117                   Cocineta
25118               Departamento
25119               Departamento
25120    Conjunto Comercial/Sala
Name: Tipo, Length: 25121, dtype: object

In [27]:
datos[['Habitaciones','Valor']]

       Habitaciones    Valor
0                 1   5950.0
1                 2  24500.0
2                 0  18200.0
3                 1   2800.0
4                 1   2800.0
...             ...      ...
25116             0  49000.0
25117             0   2800.0
25118             2   4900.0
25119             2  10500.0
25120             0  22750.0

[25121 rows x 2 columns]

In [30]:
datos.Tipo.unique()

array(['Cocineta', 'Casa', 'Conjunto Comercial/Sala', 'Departamento',
       'Casa de Condominio', 'Edificio Completo', 'Departamento en Hotel',
       'Tienda/Salón', 'Casa Comercial', 'Casa de Vecindad',
       'Terreno Estándar', 'Cochera/Estacionamiento', 'Loft',
       'Galpón/Depósito/Almacén', 'Tienda en Centro Comercial', 'Rancho',
       'Posada/Chalé', 'Estudio', 'Hotel', 'Loteo/Condominio',
       'Industria'], dtype=object)

In [31]:
inmuebles_comerciales = ['Cocineta', 'Casa', 'Conjunto Comercial/Sala', 'Departamento',
       'Casa de Condominio', 'Edificio Completo', 'Departamento en Hotel',
       'Tienda/Salón', 'Casa Comercial', 'Casa de Vecindad',
       'Terreno Estándar', 'Cochera/Estacionamiento', 'Loft',
       'Galpón/Depósito/Almacén', 'Tienda en Centro Comercial', 'Rancho',
       'Posada/Chalé', 'Estudio', 'Hotel', 'Loteo/Condominio',
       'Industria']

In [32]:
datos.query('@inmuebles_comerciales in Tipo')

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
0,Cocineta,Condesa,1,0,0,40,5950.0,1750.0,210.0
1,Casa,Polanco,2,0,1,100,24500.0,NaN,NaN
2,Conjunto Comercial/Sala,Santa Fe,0,4,0,150,18200.0,14070.0,3888.5
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN
...,...,...,...,...,...,...,...,...,...
25116,Cochera/Estacionamiento,Centro Histórico,0,0,0,755,49000.0,NaN,NaN
25117,Cocineta,Centro Histórico,0,0,0,27,2800.0,1225.0,87.5
25118,Departamento,Mixcoac,2,1,0,48,4900.0,1781.5,129.5
25119,Departamento,Lomas de Chapultepec,2,0,0,70,10500.0,2660.0,NaN
25120,Conjunto Comercial/Sala,Centro Histórico,0,0,0,250,22750.0,14721.0,3881.5

In [33]:
datos.query('@inmuebles_comerciales not in Tipo')

Empty DataFrame
Columns: [Tipo, Colonia, Habitaciones, Garages, Suites, Area, Valor, Condominio, Impuesto]
Index: []